export const styles = {
    section:
        'bg-gradient-to-br from-primary/5 via-background to-primary/5 py-12 md:py-16 dark:from-primary/10 dark:via-background dark:to-primary/10',
    container: 'container mx-auto px-4',
    header: 'mb-10 text-center',
    title: 'mb-3 text-3xl font-bold text-foreground md:text-4xl',
    description: 'mx-auto max-w-2xl text-muted-foreground',
    swiper: 'pb-12',
    swiperWrapperClass: 'testimonials-swiper',
    card: 'h-full rounded-2xl border border-border bg-card p-6 shadow-md transition-smooth hover:shadow-xl',
    quoteIcon: 'mb-4',
    quoteIconSvg: 'h-10 w-10 text-primary/20 dark:text-primary/30',
    rating: 'mb-4 flex items-center gap-1',
    star: 'h-5 w-5',
    starFilled: 'fill-warning text-warning',
    starEmpty: 'fill-muted text-muted',
    comment: 'mb-6 leading-relaxed text-foreground/80',
    userInfo: 'flex items-center gap-4 border-t border-border pt-4',
    avatar: 'h-12 w-12 rounded-full object-cover',
    userDetails: 'flex-1',
    userNameRow: 'flex items-center gap-2',
    userName: 'font-semibold text-foreground',
    verifiedBadge: 'rounded-full bg-success/10 px-2 py-0.5 text-xs text-success',
    date: 'text-sm text-muted-foreground',
} as const;
